weatherforecast_app/weather_backend/urls.py
from django.urls import path
# from .views import weather_forecast, get_weather_forecast, receive_weather_forecast
from weather_backend import views

urlpatterns = [
    # Other URL patterns
    path('weather_forecast', views.weather_forecast,name="weather_forecast"),
    # path('home', views.home,name="home"),
    path('get_weather_forecast', views.get_weather_forecast,name="get_weather_forecast"),
    path('receive_weather_forecast', views.receive_weather_forecast,name="receive_weather_forecast"),
    path('get_weather_forecast_id/<int:id>', views.get_weather_forecast_id,name="get_weather_forecast_id"),
]

weatherforecast_app/weather_frontend/urls.py
from django.urls import path,include
from django.contrib import admin
from weather_frontend import views

urlpatterns = [
    path('front_weather_forecast', views.front_weather_forecast,name="front_weather_forecast"),
    path('front_get_weather_forecast', views.front_get_weather_forecast,name="front_get_weather_forecast"),
    path('front_get_weather_forecast_id/<int:id>', views.front_get_weather_forecast_id,name="front_get_weather_forecast_id"),
]

weatherforecast_app/weatherforecast_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather_backend/', include(('weather_backend.urls','weather_backend'),namespace="weather_backend")),
    path('weather_frontend/', include(('weather_frontend.urls','weather_frontend'),namespace="weather_frontend")),
]

weatherforecast_app/templates/add_weather_forecast.html
<!DOCTYPE html>
<html>
<head>
        {% load static %}
    <title>Weather Forecast</title>
    <!-- Include the necessary CSS and JavaScript files for Google Maps -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2LCIWk4FbTrFZb_hItHNuFCfN4jpKtcI&libraries=places"></script>

      <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'css/add.css' %}" />

    <!-- Initialize the Google Map after the page has loaded -->
    <script>
        window.addEventListener('load', function() {
            initMap();
        });
    </script>

</head>
<body>
    <h1>Weather Forecast</h1>

    <div id="map-container"></div>

    <form method="POST" action="# " enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input__box">
            <label for="latitude" class="">latitude</label>
            <input type="text" id="latitude" name="latitude">
        </div>
        <div class="input__box">
            <label for="longitude" class="">longitude</label>
            <input type="text" id="longitude" name="longitude">
        </div>
        <label for="detailing_type">Detailing Type:</label>
        <select name="detailing_type" id="detailing_type">
            <option value="Hourly">Hourly</option>
            <option value="Daily">Daily</option>
            <!-- Add more options if needed -->
        </select>
        <br>
        <button type="submit">Get Weather Forecast</button>

    </form>


    <script>
        // Function to initialize the Google Map
        function initMap() {
            // Create a map instance
            var map = new google.maps.Map(document.getElementById('map-container'), {
                center: {lat: 19.0760, lng: 72.8777}, // Centered on Mumbai
                zoom: 12
            });

            // Create a marker for the selected location
            var marker = new google.maps.Marker({
                map: map,
                draggable: true
            });

            // Listen for the 'dragend' event to update the latitude and longitude input fields
            marker.addListener('dragend', function() {
                var position = marker.getPosition();
                document.getElementById('latitude').value = position.lat().toFixed(6);
                document.getElementById('longitude').value = position.lng().toFixed(6);
            });

            // Add a click event listener to the map to allow location selection
            map.addListener('click', function(event) {
                var clickedLocation = event.latLng;
                marker.setPosition(clickedLocation);
                document.getElementById('latitude').value = clickedLocation.lat().toFixed(6);
                document.getElementById('longitude').value = clickedLocation.lng().toFixed(6);
            });
            
        }
        
    </script>
    
</body>
</html>

weatherforecast_app/templates/get_allweather.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Forecast</title>
    <link rel="stylesheet" href="{% static 'css/view.css' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
      <!-- CSS only -->
      <link rel="stylesheet" href="{% static 'css/view.css' %}" />
    <style>

    </style>
    </head>
    <body>
    <div class="content">
        {% if messages %}
        <div class="row justify-content-center">
        <div class="col-sm-6">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{ message }}
            </div>
            {% endfor %}
        </div>
        </div>
        {% endif %}

        <div class="my-4">
        <a href="{% url 'weather_frontend:front_weather_forecast' %}" class="btn btn-primary">Add Location</a>

        </div>

        <table class="table my-3">
        <thead class="table-light">
            <tr>
            <th scope="col">ID</th>
            <th scope="col">Latitude</th>
            <th scope="col">Longitude</th>
            <th scope="col">Detailing Type</th>
            <th scope="col">Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
            <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.latitude }}</td>
            <td>{{ item.longitude }}</td>
            <td>{{ item.detailing_type }}</td>
            <td>{{ item.timestamp }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>

weatherforecast_app/templates/get_weather_forecast.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/view.css' %}" />
    <style>

    </style>
</head>
<body class="bodyclass">
  <div class="content">
    {% if messages %}
    <div class="row" style="justify-content: center;">
      <div class="col-sm-6 col-sm-offset-3">
        {% for message in messages %}
        <div style="margin:15px 0px" class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
          <p style="margin:15px 0px" class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">{{ message }}</p>
        </div>
        {% endfor %}
      </div>
    </div>
    
    {% endif %}
    <form class="my-4" action="" method="post" enctype="multipart/form-data">
      <a href="{% url 'weather_frontend:front_weather_forecast' %}" class="btn btn-primary">Add Location</a>
      <a href="{% url 'weather_frontend:front_get_weather_forecast' %}" class="btn btn-primary">View All Locations</a>

      {% csrf_token %}
      <!-- {{data}} -->
      <table class="table my-3">
        <thead class="table-light">
          <tr>
            <th scope="col">Id</th>
            <th scope="col">latitude</th>
            <th scope="col">longitude</th>
            <th scope="col">detailing_type</th>
            <th scope="col">timestamp</th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td>{{data.id}}</td>
            <td>{{data.latitude}}</td>
            <td>{{data.longitude}}</td>
            <td>{{data.detailing_type}}</td>
            <td>{{data.timestamp}}</td>
          </tr>

        </tbody>
      </table>
    </form>
  </div>
</body>
</html>